environment_version: 1
credentials:
- type: general
  id: irKqOC04LRPWaKVp
  description: DOC_DB_PASSWORD
  value: DOC_DB_PASSWORD
- type: general
  id: Lmk8rAWX5EdLl3L0
  description: DOC_DB_HOST
  value: DOC_DB_HOST
- type: general
  id: KUIluZeSuzfew5sb
  description: DOC_DB_USERNAME
  value: DOC_DB_USERNAME
- type: general
  id: wBThnBgJUBzBRz45
  description: DOC_DB_SSH_USERNAME
  value: DOC_DB_SSH_USERNAME
- type: general
  id: W0GGw7qFed6TFTZK
  description: DOC_DB_SSH_PASSWORD
  value: DOC_DB_SSH_PASSWORD
- type: general
  id: X3aaTa4J7ExWFj5g
  description: DOC_DB_SSH_HOST
  value: DOC_DB_SSH_HOST
- type: aws
  id: E2sUh7HEujEu9WqT
  description: amazon
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
